name: Tests
on:
  push:
      branches:
          - "main"
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-test.txt
        - name: Run unittest
          run: |
            coverage run -m unittest
            coverage xml
        - name: Upload codecov
          uses: codecov/codecov-action@v1
          with:
            verbose: true
            flags: unittests
            file: ./coverage.xml
            fail_ci_if_error: true


                

      
