name: Run Tests and Deploy
on:
  push:
      branches:
          - "main"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-test.txt
        - name: Run unittest
          run: |
            coverage run -m unittest
            coverage xml
        - name: Upload codecov
          uses: codecov/codecov-action@v1
          with:
            verbose: true
            flags: unittests
            file: ./coverage.xml
            fail_ci_if_error: true
  deploy-heroku:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lista-de-palavras"
          heroku_email: ${{secrets.HEROKU_MAIL}}
  deploy-azure:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lista-de-palavras'
        slot-name: 'production'
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
